
package uis.edu.co.banco_de_sangre.vista;

import uis.edu.co.banco_de_sangre.controlador.CDonacion;

import java.util.HashSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uis.edu.co.banco_de_sangre.controlador.ControladorPantallas;
import uis.edu.co.banco_de_sangre.modelo.Donacion;


public class VDonacion extends javax.swing.JFrame {

     
      CDonacion cd = new CDonacion();
    /**
     * Creates new form Vdonaciones
     */
    public VDonacion() {
        initComponents();
    }
    
    public void limpiarCampos(){
    txtIdDonacion.setText("");
    txtDonante.setText("");
    txtFechaDeDonacion.setText("");
    txtCantidadSangre.setText("");
    cmbTipoDonacion.setSelectedIndex(0);
        
    }
    
    public void cargarDatos(){
    
    int fila= tblDonaciones.getSelectedRow();
    
    txtDonante.setText(tblDonaciones.getValueAt(fila, 1).toString());
    txtFechaDeDonacion.setText(tblDonaciones.getValueAt(fila, 5).toString());
    txtCantidadSangre.setText(tblDonaciones.getValueAt(fila, 6).toString());
    txtIdDonacion.setText(tblDonaciones.getValueAt(fila, 0).toString());
        
    String tipodonacion = tblDonaciones.getValueAt(fila, 7).toString();
    
    for (int i = 0; i < cmbTipoDonacion.getItemCount(); i++) {
        if (cmbTipoDonacion.getItemAt(i).equals(tipodonacion)) {
            cmbTipoDonacion.setSelectedIndex(i);
            break;
        }
    }
    
    }

    private void actualizarTablaConDonacion(Donacion donacion) {
    DefaultTableModel model = (DefaultTableModel) tblDonaciones.getModel();
    model.setRowCount(0); 

    if (donacion != null) {
        Object[] rowData = {
            donacion.getId_donacion(),
            donacion.getDonante(),
            donacion.getFecha_de_donacion(),
            donacion.getCantidad_sangre(),
            donacion.getTipo_donacion()
        };
        model.addRow(rowData);
    }
}

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbIdDonacion = new javax.swing.JLabel();
        txtIdDonacion = new javax.swing.JTextField();
        lblDonante = new javax.swing.JLabel();
        lblFechaFeDonacion = new javax.swing.JLabel();
        txtDonante = new javax.swing.JTextField();
        txtFechaDeDonacion = new javax.swing.JTextField();
        lblCantidadSangre = new javax.swing.JLabel();
        txtCantidadSangre = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonaciones = new javax.swing.JTable();
        cmbTipoDonacion = new javax.swing.JComboBox<>();
        btnInformacion = new javax.swing.JButton();
        btnCerrarDonaciones = new javax.swing.JButton();
        btnConsultarFechas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        lbIdDonacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbIdDonacion.setForeground(new java.awt.Color(255, 255, 255));
        lbIdDonacion.setText("id_donacion");

        lblDonante.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDonante.setForeground(new java.awt.Color(255, 255, 255));
        lblDonante.setText("donante");

        lblFechaFeDonacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFechaFeDonacion.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaFeDonacion.setText("fecha_de_donacion");

        txtFechaDeDonacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaDeDonacionActionPerformed(evt);
            }
        });

        lblCantidadSangre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCantidadSangre.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadSangre.setText("cantidad_sangre");

        btnConsultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Escritorio\\Bases de Datos\\Iconos\\consultar.png")); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Escritorio\\Bases de Datos\\Iconos\\registrar.png")); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Escritorio\\Bases de Datos\\Iconos\\MODIFICAR.png")); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Escritorio\\Bases de Datos\\Iconos\\eliminar.png")); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblDonaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID Donacion", "Donante", "Fecha de Donacion", "Cantidad Sangre", "Tipo Donacion"
            }));
            tblDonaciones.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblDonacionesMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(tblDonaciones);

            cmbTipoDonacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total", "Parcial", " " }));
            cmbTipoDonacion.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmbTipoDonacionActionPerformed(evt);
                }
            });

            btnInformacion.setBackground(new java.awt.Color(255, 102, 102));
            btnInformacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            btnInformacion.setForeground(new java.awt.Color(255, 255, 255));
            btnInformacion.setText("INFORMACION");
            btnInformacion.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnInformacionActionPerformed(evt);
                }
            });

            btnCerrarDonaciones.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Escritorio\\Bases de Datos\\Iconos\\cerrar.png")); // NOI18N
            btnCerrarDonaciones.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCerrarDonacionesActionPerformed(evt);
                }
            });

            btnConsultarFechas.setBackground(new java.awt.Color(255, 102, 102));
            btnConsultarFechas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            btnConsultarFechas.setForeground(new java.awt.Color(255, 255, 255));
            btnConsultarFechas.setText("BUSCAR POR FECHA");
            btnConsultarFechas.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnConsultarFechasActionPerformed(evt);
                }
            });

            jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setText("Tipo_Donacion");

            jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setText("DONACIONES");

            jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setText("CONSULTAR");

            jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setText("REGISTRAR");

            jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setText("MODIFICAR");

            jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(255, 255, 255));
            jLabel6.setText("ELIMINAR");

            jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(255, 255, 255));
            jLabel7.setText("CERRAR");

            jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Escritorio\\Bases de Datos\\Iconos\\CRUZ ROJA 1.png")); // NOI18N

            jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Escritorio\\Bases de Datos\\Iconos\\CRUZ ROJA 1.png")); // NOI18N

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbIdDonacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDonante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFechaFeDonacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFechaDeDonacion, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDonante, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtIdDonacion)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblCantidadSangre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel5))
                                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCantidadSangre)
                                                .addComponent(cmbTipoDonacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel6)))
                                            .addGap(103, 103, 103))))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addComponent(btnCerrarDonaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(191, 191, 191)
                            .addComponent(btnConsultarFechas)
                            .addGap(125, 125, 125))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(419, 419, 419)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbIdDonacion)
                                .addComponent(txtIdDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDonante)
                                .addComponent(txtDonante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFechaFeDonacion)
                                .addComponent(txtFechaDeDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCantidadSangre)
                                .addComponent(txtCantidadSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbTipoDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGap(8, 8, 8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCerrarDonaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel7)
                    .addContainerGap(16, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtFechaDeDonacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaDeDonacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaDeDonacionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       // TODO add your handling code here:
     
    String idDonacionStr = txtIdDonacion.getText().trim();
    String donanteStr = txtDonante.getText().trim();
    String fechaDeDonacion = txtFechaDeDonacion.getText().trim();
    String cantidadSangreStr = txtCantidadSangre.getText().trim();
    String tipoDonacion = cmbTipoDonacion.getSelectedItem().toString();
    
    
    if (idDonacionStr.isEmpty() || donanteStr.isEmpty() || fechaDeDonacion.isEmpty() || cantidadSangreStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
     
    int id_donacion = Integer.parseInt(idDonacionStr);
    int donante = Integer.parseInt(donanteStr);
    double cantidad_sangre = Double.parseDouble(cantidadSangreStr);
    

    Donacion d = new Donacion(id_donacion, donante, fechaDeDonacion, cantidad_sangre, tipoDonacion);
    
    
    cd.registrardonaciones(d);
    
    limpiarCampos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbTipoDonacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDonacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoDonacionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cd.cargarTablaDonaciones(tblDonaciones);
        int proximoId = cd.obtenerProximoIdDonacion();
        txtIdDonacion.setText(String.valueOf(proximoId));
    }//GEN-LAST:event_formWindowOpened

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
 String idDonanteStr = JOptionPane.showInputDialog(null, "Ingrese el ID del donante:");
    if (idDonanteStr != null && !idDonanteStr.isEmpty()) {
        try {
            int idDonante = Integer.parseInt(idDonanteStr);
            
            CDonacion cd = new CDonacion();
            cd.consultarTablaDonacionesPorDonante(tblDonaciones, idDonante);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido para el ID del donante.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Debe ingresar un ID de donante.");
    }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
 
        int idDonacion = Integer.parseInt(txtIdDonacion.getText());
        int donante = Integer.parseInt(txtDonante.getText());
        String fechaDeDonacion = txtFechaDeDonacion.getText();
        double cantidadSangre = Double.parseDouble(txtCantidadSangre.getText());
        String tipoDonacion = (String) cmbTipoDonacion.getSelectedItem();

       
        Donacion donacion = new Donacion(idDonacion, donante, fechaDeDonacion, cantidadSangre, tipoDonacion);

        
        cd.modificarDonacion(donacion);

        
        cd.cargarTablaDonaciones(tblDonaciones);
        
        
        limpiarCampos();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Por favor ingrese valores válidos para los campos numéricos.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Ocurrió un error al modificar la donación: " + ex.getMessage());
    }
        

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

  try {
        int id_donacion = Integer.parseInt(txtIdDonacion.getText());

        
        CDonacion cd = new CDonacion();
        boolean eliminado = cd.eliminarDonacion(id_donacion);

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Donación eliminada correctamente.");
           
            cd.cargarTablaDonaciones(tblDonaciones);  
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar la donación.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID de donación válido.");
    }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        
        cd.cargarTablaDonaciones(tblDonaciones);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
       
        
    JOptionPane.showMessageDialog(this,
        "Banco de Sangre\n cruz roja colombiana" +
        "Versión: 1.0\n" +
        "Desarrollado por: Vera&Soto asociados\n" +
        "Fecha: 2024\n" +
        "Esta aplicación permite gestionar las donaciones y los donantes.",
        "Información",
        JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btnInformacionActionPerformed

    private void btnCerrarDonacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarDonacionesActionPerformed
        // TODO add your handling code here:
       
    int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres cerrar la ventana de donaciones?", "Confirmación", JOptionPane.YES_NO_OPTION);
    
    
    if (opcion == JOptionPane.YES_OPTION) {
        
        ControladorPantallas.cerrarPantallaDonacion();
    }
    }//GEN-LAST:event_btnCerrarDonacionesActionPerformed

    private void tblDonacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonacionesMouseClicked
      cargarDatos();
    }//GEN-LAST:event_tblDonacionesMouseClicked

    private void btnConsultarFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarFechasActionPerformed
        // TODO add your handling code here:
    String fechaInicio = JOptionPane.showInputDialog(this, "Ingrese la fecha de inicio (YYYY-MM-DD):");
    String fechaFin = JOptionPane.showInputDialog(this, "Ingrese la fecha de fin (YYYY-MM-DD):");

    if (fechaInicio != null && fechaFin != null) {
        CDonacion cd = new CDonacion();
        cd.consultarDonacionesPorFechas(tblDonaciones, fechaInicio, fechaFin);
    } else {
        JOptionPane.showMessageDialog(this, "Por favor ingrese fechas válidas.");
    }
    }//GEN-LAST:event_btnConsultarFechasActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VDonacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarDonaciones;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarFechas;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbTipoDonacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIdDonacion;
    private javax.swing.JLabel lblCantidadSangre;
    private javax.swing.JLabel lblDonante;
    private javax.swing.JLabel lblFechaFeDonacion;
    private javax.swing.JTable tblDonaciones;
    private javax.swing.JTextField txtCantidadSangre;
    private javax.swing.JTextField txtDonante;
    private javax.swing.JTextField txtFechaDeDonacion;
    private javax.swing.JTextField txtIdDonacion;
    // End of variables declaration//GEN-END:variables
}
